spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/restaurantdb}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: data-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "xyz.vanez.dto.*"
        spring.json.type.mapping: reviewMessage:xyz.vanez.dto.ReviewMessage
    listener:
      ack-mode: manual_immediate
      concurrency: 3       
  lifecycle:
    timeout-per-shutdown-phase: 30s

management:
endpoints:
  web:
    exposure:
      include: health,info
endpoint:
  health:
    show-details: always